#!/bin/bash
if [ $# -ne 1 ]; then
echo "Usage: $0 <4-digit-integer>"
exit 1
fi


if [[ ${#1} -ne 4 ]]; then
echo "Error: Ο αριθμός πρέπει αν είναι 4-ψήφιος"
exit 1
elif [[ ! $1 =~ ^[0-9]+$ ]]; then
echo "Error: To input πρέπει να είναι αριθμός. "
exit 1
fi

input=$1
hash=$(echo -n "$input" | sha256sum | awk '{print $1}')

echo "Output of the LAST 4 digit integer: $hash"

